{{- if .Values.istio.enabled -}}
kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ .Chart.Name }}
spec:
  servers:
    - hosts:
    {{- range .Values.istio.hostNames }}
        - {{ . }}
    {{- end }}
      port:
        name: https
        number: 443
        protocol: HTTP
      tls:
        httpsRedirect: false
    - hosts:
    {{- range .Values.istio.hostNames }}
        - {{ . }}
    {{- end }}
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
  selector:
    app: {{ .Values.istio.ingressGatewayName }}
{{- end }}
