{{- if .Values.terraformCloud.enable -}}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: atlantis-terraform-cloud
  labels:
    app: {{ template "atlantis.name" . }}
    chart: {{ template "atlantis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  backendType: systemManager
  data:
    - key: {{ .Values.externalSecrets.terraformCloudSsm }} 
      name: terraform_cloud_token
  template:
    metadata:
      annotations:
        owner: alan.lee@procore.com
{{- end -}}
