version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      debian:
        patterns:
        - "debian"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/tools/benchstat"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/tools/betteralign"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/tools/gofumpt"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/tools/goimports"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/tools/golangci-lint"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
