ingress:
  enabled: false

service:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - "192.30.252.0/22"
    - "185.199.108.0/22"
    - "140.82.112.0/20"
    - "34.103.73.76/32"

serviceAccount:
  name: atlantis
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::220696059325:role/atlantis-ops-role

environmentSecrets:
  # - name: GH_APP_KEY_FILE
  #   secretKeyRef:
  #     name: atlantis-secret
  #     key: github_app_key_file
  - name: GH_WEBHOOK_SECRET
    secretKeyRef:
      name: atlantis-secret
      key: github_token

environment:
  GH_APP_ID: 113650
  GH_APP_KEY_FILE: /atlantis_keys/gh_app_key_file.pem

github: null

extraVolumes:
  - name: gh-app-key-file
    secret:
      secretName: atlantis-secret
      items:
        - key: github_app_key_file
          path: gh_app_key_file.pem

extraVolumeMounts:
  - mountPath: /atlantis_keys/
    name: gh-app-key-file
