ingress:
  enabled: false

service:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - "192.30.252.0/22"
    - "185.199.108.0/22"
    - "140.82.112.0/20"
    - "34.103.73.76/32"

serviceAccount:
  name: atlantis
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::749942219478:role/atlantis-ops-role

environmentSecrets:
  - name: ATLANTIS_WRITE_GIT_CREDS
    secretKeyRef:
      name: atlantis-secret
      key: atlantis_write_git_creds

