name: Benchmark Go code

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          show-progress: false

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.ver
          cache: false

      - name: Fetch test rules
        run: make -C cmd/pint/bench fetch

      - name: Benchmark PR branch
        run: |
          make benchmark | tee new.txt

      - name: Benchmark main branch
        run: |
          git fetch origin main
          git reset --hard FETCH_HEAD
          make benchmark | tee old.txt

      - name: Diff benchmarks
        run: |
          git reset --hard ${GITHUB_SHA}
          make benchmark-diff

      - name: Report
        if: ${{ github.event.pull_request.head.repo.full_name == 'cloudflare/pint' }}
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # v2.5.0
        with:
          filePath: benchstat.txt
          comment_tag: benchstat
