name: "Dependency Review"
on: [pull_request]

permissions: read-all

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: "Dependency Review"
        uses: actions/dependency-review-action@v4

  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          show-progress: false

      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: stable
          check-latest: true
