name: Spellcheck
on: [pull_request]

permissions: read-all

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.41.0
        with:
          config_path: .github/spellcheck/config.yml

  markdown:
    name: Markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Markdownlint
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: ".markdownlint.json"
