# To run locally, run `make lint` from the root of the repo.
name: Golang Linter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
