name: Test Go code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.ver
          cache: false

      - name: Test
        run: make test

      - name: Check for local changes
        run: git diff --exit-code

      # Codecov reporting is unreliable.
      # Re-run report 3 times to have a better
      # chance of success.
      - name: Report code coverage (1)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.cover/coverage.out
          fail_ci_if_error: true
          handle_no_reports_found: true
        continue-on-error: true

      - name: Report code coverage (2)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.cover/coverage.out
          fail_ci_if_error: true
          handle_no_reports_found: true
        continue-on-error: true

      - name: Report code coverage (3)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.cover/coverage.out
          fail_ci_if_error: true
          handle_no_reports_found: true
