# To run locally, run `make test` from the root of the repo.
name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - uses: actions/checkout@v3
      - name: Run Go tests
        run: make test
